### ISSUE TITLE
Github Drawer Link Broken

### ISSUE THREAD

**Issue by TravisGibbs** [TravisGibbs/SportsCardToolApp#46]
When the drawer is the active navigation UI the Github link doesn’t redirect properly. Should redirect to https://github.com/TravisGibbs/SportsCardToolLib .

Image:
![IMG_5645](https://github.com/TravisGibbs/SportsCardToolApp/assets/28307522/a9095eac-e776-47a3-9a14-a694ac988e60)

Notice the empty page that it is directed to.

**Comment by achhayapathak** [comment]
can you attach a screenshot of the problem

**Comment by TravisGibbs** [comment]
@achhayapathak I updated the issue with an image of that helps. Thank you for your interest!

**Comment by aAYUSHkujur** [comment]
Hi, @TravisGibbs I have fixed the issue and created the PR. Please feel free to review it. Thank You
